### ISSUE TITLE
redux-hook和router-hook

### ISSUE THREAD

**Issue by yeyeyehui** [uglyspoon/h5-cloud-music-ts#13]
作者您好，我在看这个项目的时候，您这边用的hook，但是状态管理和路由还是用的connect和withRouter，我使用hook改造的时候发现是@type版本太低，没有导出hook，所以报错，您这边是遇到这样的问题而没有使用hook吗？

**Comment by uglyspoon** [comment]
因为这个项目是按着 [这个项目](https://github.com/sanyuan0704/react-cloud-music)写的ts版本，所以路由什么的没变。
