### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by qinggege2016** [uglyspoon/h5-cloud-music-ts#15]
![image](https://user-images.githubusercontent.com/23027097/147366601-824b9e8e-2f89-4967-a689-9dd95b143e48.png)

![image](https://user-images.githubusercontent.com/23027097/147366654-a4784cb4-88c5-45e7-8c41-0fba82355590.png)

**Comment by qinggege2016** [comment]
对node版本有限制吗，install全成功了就是启动不了

**Comment by uglyspoon** [comment]
> 对node版本有限制吗，install全成功了就是启动不了

是的，估计是你的node版本太高了，我机子上的node版本是12.x的版本，你可以切换试试

**Comment by uglyspoon** [comment]
> 对node版本有限制吗，install全成功了就是启动不了

导致你项目启动不了的是第一个截图的报错(error)，这个应该是node版本太高导致 你可以切换到node@12试试；
第二个图的报错，查了下解决方法[链接](https://stackoverflow.com/questions/70150683/using-react-with-redux-and-getting-error-in-redux-expected)，是thunk这个包的版本问题，我会推个新版本，你更新下就好
