### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by bgwd666** [uglyspoon/h5-cloud-music-ts#4]
./src/containers/Player/index.tsx
Cannot find file: 'index.tsx' does not match the corresponding name on disk: '.\src\components\ProgressCircle\progressCircle'.
一开始是那个ProgressCircle 要小写

然后 ,我明明在 tsconfig 忽略了 node_modules 却还报错
F:/360MoveData/Users/Administrator/Desktop/h5-cloud-music-ts/node_modules/_jest-diff@26.0.1@jest-diff/build/diffLines.d.ts
TypeScript error in F:/360MoveData/Users/Administrator/Desktop/h5-cloud-music-ts/node_modules/_jest-diff@26.0.1@jest-diff/build/diffLines.d.ts(8,13):
'=' expected.  TS1005

     6 |  */
     7 | import { Diff } from './cleanupSemantic';
  >  8 | import type { DiffOptions } from './types';
       |             ^
     9 | export declare const diffLinesUnified: (aLines: string[], bLines: string[], options?: DiffOptions | undefined) => string;
    10 | export declare const diffLinesUnified2: (aLinesDisplay: string[], bLinesDisplay: string[], aLinesCompare: string[], bLinesCompare: string[], options?: DiffOptions |
undefined) => string;
    11 | export declare const diffLinesRaw: (aLines: string[], bLines: string[]) => Diff[];

**Comment by bgwd666** [comment]
找到原因了, 依赖问题 packge.json 里面 typescript 版本要 大于 3.8, 安装最新的

**Comment by bestFeeling** [comment]
ts 3.9.5，还是一堆ts报错，跑不起来

**Comment by xiawnag** [comment]
Failed to compile.

./src/containers/Player/index.tsx
Cannot find file: 'index.tsx' does not match the corresponding name on disk: '.\src\components\ProgressCircle\progressCircle'.

**Comment by uglyspoon** [comment]
> Failed to compile.
> 
> ./src/containers/Player/index.tsx
> Cannot find file: 'index.tsx' does not match the corresponding name on disk: '.\src\components\ProgressCircle\progressCircle'.

这个是文件夹大小写的问题，git commit对系统的大小写问题不敏感，现已解决
